[package]
name = "game"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.17.3"
bevy-inspector-egui = { version = "0.35.0", optional = true }
bevy_egui = { version = "0.38.1", optional = true }

[features]
default = []
dev = ["dep:bevy-inspector-egui", "dep:bevy_egui"]
